version: 2.1

orbs:
  macos: circleci/macos@2.3.4

executors:
  mac:
    parameters:
      xcode:
        type: string
    macos:
      xcode: << parameters.xcode >>
      resource_class: macos.x86.medium.gen2
commands:
  capture:
    parameters:
      after:
        type: integer
        default: 60
    steps:
      - run: sleep << parameters.after >>
      - run: screencapture -m -D 1 -C captured_<< parameters.after >>.png
      - store_artifacts:
          path: captured_<< parameters.after >>.png
jobs:
  screencapture:
    parameters:
      xcode:
        type: string
    executor:
      name: mac
      xcode: << parameters.xcode >>
    steps:
      - macos/add-uitest-permissions
      - macos/add-permission:
          bundle-id: "com.apple.Terminal"
          permission-type: "kTCCServiceScreenCapture"
      # ref: https://support.circleci.com/hc/en-us/articles/4405324304155
      - run: /Library/Application\ Support/VMware\ Tools/vmware-resolutionSet 1024 768
      - run: open https://fast.com
      - capture:
          after: 20

workflows:
  main:
    jobs:
      - screencapture:
          matrix:
            parameters:
              xcode:
                - '14.1.0'
                - '13.4.1'
