version: 2.1

commands:
  xz-info:
    steps:
      - run: brew info xz

jobs:
  inspect:
    parameters:
      xcode:
        type: string
      rc:
        type: string
    macos:
      xcode: << parameters.xcode >>
    resource_class: << parameters.rc >>
    steps:
      - xz-info

workflows:
  inspect:
    jobs:
      - inspect:
          matrix:
            parameters:
              rc:
                - macos.m1.medium.gen1
              xcode:
                - 15.3.0
                - 15.4.0
                - 15.1.0
                - 14.3.1
                - 14.2.0
