version: 2.1

jobs:
  python:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.medium.gen1
    steps:
      - run: which pyenv
      - run:
          name: check Python
          command: |
            # should be 3.11.3
            which python
            python --version
      - run: pyenv global 3.11.3
      - run: python --version

workflows:
  main:
    jobs:
      - python
