version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  build:
    macos:
      xcode: 14.2
      resource_class: macos.m1.large.gen1
    steps:
      - run: sudo softwareupdate --install-rosetta
      - aws-cli/install
    
