version: 2.1

jobs:
  firebase:
    parameters:
      xcode:
        type: string
        default: 13.2.0
    macos:
      xcode: << parameters.xcode >>
    steps:
      - run: |
          curl -svL https://firebase.tools | upgrade=true bash

workflows:
  main:
    jobs:
      - firebase:
          matrix:
            parameters:
              # See https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
              xcode:
                - 13.2.1

