version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  macos: circleci/macos@2.3

jobs:
  build:
    macos:
      xcode: 15.0
    resource_class: macos.m1.medium.gen1
    environment:
      AWS_PAGER: ""
    steps:
      - macos/install-rosetta
      - aws-cli/setup
      - run: aws sts get-caller-identity
      - run:
          name: generate large files
          command: |
            mkdir m1
            mkfile -n 1g m1/tmp_1GB_dummy
            mkfile -n 5g m1/tmp_5GB_dummy
            mkfile -n 1og m1/tmp_10GB_dummy
            ls -lah m1
      - run:
          name: upload to S3
          command: time aws s3 sync --only-show-errors m1 s3://kelvintaywl-macos-upload/
