version: 2.1

jobs:
  firebase-no-upgrade:
    parameters:
      xcode:
        type: string
        default: 13.4.1
    macos:
      xcode: << parameters.xcode >>
    steps:
      - run: |
          curl -svL https://firebase.tools | bash
  firebase-with-upgrade:
    parameters:
      xcode:
        type: string
        default: 13.4.1
    macos:
      xcode: << parameters.xcode >>
    steps:
      - run: |
          # the upgrade=true is seen on https://firebase.google.com/docs/cli#macos
          curl -svL https://firebase.tools | upgrade=true bash
workflows:
  main:
    jobs:
      - firebase-no-upgrade
      - firebase-with-upgrade

