version: 2.1

orbs:
  dummy: kelvintaywl/dummy-private@0.1.0

commands:
  inspect-bash-profile:
    steps:
      - run:
          name: cat BASH profile
          command: |
            cat -e $HOME/.bash_profile

jobs:
  burger:
    parameters:
      xcode:
        type: string
    macos:
      xcode: << parameters.xcode >>
    steps:
      - dummy/greet

workflows:
  main:
    jobs:
      - burger
