version: 2.1

orbs:
  node: circleci/node@5

jobs:
  node-install:
    parameters:
      xcode:
        type: string
        default: "12.5.1"
    macos:
      xcode: << parameters.xcode >>
    resource_class: macos.x86.medium.gen2
    steps:
      - run: which node && node -v
      - run:
          name: install npm
          command: |
            echo "export YARN_VERSION=1.22.5" >> $BASH_ENV
            echo "export NODE_VERSION=14.17.5" >> $BASH_ENV
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.37.2/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install $NODE_VERSION' >> $BASH_ENV
            echo 'nvm use $NODE_VERSION' >> $BASH_ENV
            echo 'nvm alias default $NODE_VERSION' >> $BASH_ENV
      - run:
          name: check
          command: |
            node -v
            which node

            npm -v
            which npm

            nvm -v

workflows:
  main:
    jobs:
      - node-install
