version: 2.1

jobs:
  build-macos:
    macos:
      xcode: 11.7.0
    resource_class: macos.x86.medium.gen2
    steps:
      - run: |
          which python3
          python3 --version
      - run: |
          python3 -m pip install -q awscli
          python3 -m pip list

workflows:
  main:
    jobs:
      - build-macos
