version: 2.1

orbs:
  macos: circleci/macos@2.3.6

commands:
  selenium-webdriver:
    steps:
      - run: defaults write com.apple.Safari IncludeDevelopMenu 1
      # - run: defaults write com.apple.Safari BlockStoragePolicy 1
      - run: sudo safaridriver --enable
      - macos/add-permission:
          bundle-id: com.apple.Terminal
          permission-type: kTCCServiceAppleEvents
      - macos/add-safari-permissions
      - run: safaridriver --version
      - run: ruby -v
      - checkout
      - run: bundle install
      - run: bundle exec ruby reproduce.rb
  check-spec:
    steps:
      - run:
          name: check OS
          command: uname
      - run:
          name: check arch
          command: uname -m
      - run:
          name: check Node
          command: which node && node -v
      - run:
          name: check SafariDriver
          command: safaridriver --version
      - run:
          name: check Python
          command: |
            which python && python --version
            which python3 && python3 --version
      - run:
          name: check Ruby
          command: |
            ruby --version
            bundler --version

jobs:
  burger:
    parameters:
      xcode:
        type: string
        default: 12.5.1
      resource:
        # https://circleci.com/docs/using-macos/#available-resource-classes
        type: enum
        enum:
          - macos.x86.medium.gen2
          - macos.m1.medium.gen1
          - macos.m1.large.gen1
        default: macos.x86.medium.gen2
    macos:
      xcode: << parameters.xcode >>
    resource_class: << parameters.resource >>
    steps:
      - selenium-webdriver

workflows:
  main:
    jobs:
      - burger:
          matrix:
            parameters:
              resource:
                - macos.x86.medium.gen2
                - macos.m1.medium.gen1
              xcode:
                - 14.3.1
