version: 2.1

jobs:
  build-macos:
    macos:
      xcode: 11.7.0
    resource_class: macos.x86.medium.gen2
    steps:
      - run: |
          mkdir deps
          git clone git@github.com:RedisLabsModules/readies.git deps/readies
      - run: |
          ./deps/readies/bin/getpy3
          ./deps/readies/bin/getaws
          python3 --version
          python3 -m pip list

workflows:
  main:
    jobs:
      - build-macos
