version: 2.1

jobs:
  burger:
    macos:
      xcode: 13.2.0
    steps:
      - run:
          name: Inspect BASH profile
          command: |
            cat -e $HOME/.bash_profile

workflows:
  main:
    jobs:
      - burger
