version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  macos: circleci/macos@2.3

jobs:
  build:
    macos:
      xcode: 15.0
    resource_class: macos.x86.medium.gen2
    environment:
      AWS_PAGER: ""
    steps:
      - macos/install-rosetta
      - aws-cli/setup
      - run: aws sts get-caller-identity
      - run:
          name: generate large files
          command: |
            mkdir m1
            mkfile -n 100m m1/tmp_100MB_dummy
            mkfile -n 200m m1/tmp_200MB_dummy
            ls -lah m1
      # Fix attempt: https://support.circleci.com/hc/en-us/articles/19334402064027-Troubleshooting-slow-uploads-to-S3-for-jobs-using-an-m1-macOS-resource-class
      - run: sudo sysctl net.inet.tcp.tso=0
      - run:
          name: upload to S3
          command: time aws s3 sync --only-show-errors m1 s3://kelvintaywl-macos-upload/
