version: 2.1

commands:
  check-spec:
    steps:
      - run:
          name: check OS
          command: uname
      - run:
          name: check arch
          command: uname -m

jobs:
  burger:
    parameters:
      xcode:
        type: string
        default: 14.2.0
      resource:
        # https://circleci.com/docs/using-macos/#available-resource-classes
        type: enum
        enum:
          - macos.x86.medium.gen2
          - macos.m1.large.gen1
          - large
        default: macos.x86.medium.gen2
    macos:
      xcode: << parameters.xcode >>
    resource_class: << parameters.resource >>
    steps:
      - check-spec

workflows:
  main:
    jobs:
      - burger:
          matrix:
            parameters:
              resource:
                - macos.m1.large.gen1
                - macos.x86.medium.gen2
                - large
