version: 2.1

jobs:
  build:
    macos:
      xcode: 15.3.0
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - run:
          environment:
            GEM_PATH: /tmp/bundle
          name: install deps
          command: |
            #!/bin/bash
            bundle config set --local path $GEM_PATH
            bundle check || bundle install
      - run:
          name: check deps
          command: |
            bundle list
            bundle info nokogiri
            
