version: 2.1

commands:
  test-curl:
    steps:
      - run: which curl && curl --version
      - run: |
          docker pull kelvintaywl/fancy-nginx
          docker image save kelvintaywl/fancy-nginx -o nginx.tar
      - run: |
          curl -v -X POST -T nginx.tar https://eobg3z91sw5j8pt.m.pipedream.net

  check-spec:
    steps:
      - run:
          name: check OS
          command: uname
      - run:
          name: check arch
          command: uname -m
      - run:
          name: check Node
          command: which node && node -v
      - run:
          name: check Python
          command: |
            which python && python --version
            which python3 && python3 --version
      - run:
          name: check Ruby
          command: |
            ruby --version
            bundler --version

jobs:
  burger:
    parameters:
      xcode:
        type: string
        default: 12.5.1
      resource:
        # https://circleci.com/docs/using-macos/#available-resource-classes
        type: enum
        enum:
          - macos.x86.medium.gen2
          - macos.m1.large.gen1
          - medium
          - large
        default: macos.x86.medium.gen2
    macos:
      xcode: << parameters.xcode >>
    resource_class: << parameters.resource >>
    steps:
      - test-curl

workflows:
  main:
    jobs:
      - burger:
          matrix:
            parameters:
              resource:
                - macos.m1.large.gen1
                - large
              xcode:
                - 14.3.1
                - 14.1.0
