version: 2.1

jobs:
  terraform-init:
    parameters:
      tls-version:
        type: string
        default: '3.2.0'
    macos:
      xcode: 12.5.1
    resource_class: macos.m1.large.gen1
    steps:
      - run:
          name: install TF
          command: |
            brew install terraform
            terraform version
      - run:
          name: Setup TF file
          command: |
            cat > main.tf \<< 'EOL'
            terraform {
              required_providers {
                tls = {
                  source = "hashicorp/tls"
                  version = "<< parameters.tls-version >>"
                }
              }
            }

            provider "tls" {
              # Configuration options
            }
            EOL
      - run: cat main.tf
      - run: terraform init

workflows:
  main:
    jobs:
      - terraform-init:
          matrix:
            parameters:
              tls-version:
                - "3.1.0"
                - "3.2.0"
                - "4.0.5"  # latest
