version: 2.1

orbs:
  dummy: kelvintaywl/dummy-private@0.1.0

commands:
  inspect-bash-profile:
    steps:
      - run:
          name: cat BASH profile
          command: |
            cat -e $HOME/.bash_profile

jobs:
  burger:
    parameters:
      xcode:
        type: string
        default: 13.2.0
    macos:
      xcode: << parameters.xcode >>
    steps:
      - inspect-bash-profile
      - run:
          name: Add Newline
          command: |
            printf "\n" >> $HOME/.bash_profile
      - inspect-bash-profile

workflows:
  main:
    jobs:
      - burger
