version: 2.1

jobs:
  python:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.medium.gen1
    steps:
      - run: which pyenv
      - run:
          name: check Python
          command: |
            # should be 3.11.3
            which python
            python --version
      - run:
          name: check Python3
          command: |
            which python3
            python3 --version
      - run:
          name: run Python script
          # NOTE: important to use python, not python3
          shell: '/usr/bin/env python'
          command: |
            import sys

            print("Python version")
            print (sys.version)
            print("Version info.")
            print (sys.version_info)

workflows:
  main:
    jobs:
      - python
