version: 2.1

jobs: # a basic unit of work in a run
  build: # your job name
    macos:
      xcode: 12.5.1 # indicate your selected version of Xcode
    environment:
      HTTPS_PROXY: "https://invalid"
      HTTP_PROXY: "http://invalid"
      https_proxy: "https://invalid"
      htt_proxy: "http://invalid"
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          command: curl http://www.google.com
