version: 2.1

executors:
  mac:
    macos:
      xcode: 14.1.0
      resource_class: macos.x86.medium.gen2
commands:
  capture:
    parameters:
      after:
        type: integer
        default: 60
    steps:
      - run: sleep << parameters.after >>
      - run: screencapture captured_<< parameters.after >>.png
      - store_artifacts:
          path: captured_<< parameters.after >>.png
jobs:
  screencapture:
    executor: mac
    steps:
      - capture:
          after: 60

workflows:
  main:
    jobs:
      - screencapture
