version: 2.1

orbs:
  macos: circleci/macos@2.3.4

executors:
  mac:
    macos:
      xcode: 14.1.0
      resource_class: macos.x86.medium.gen2
commands:
  capture:
    parameters:
      after:
        type: integer
        default: 60
    steps:
      - run: sleep << parameters.after >>
      - run: screencapture captured_<< parameters.after >>.png
      - store_artifacts:
          path: captured_<< parameters.after >>.png
jobs:
  screencapture:
    executor: mac
    steps:
      - macos/add-uitest-permissions
      - macos/add-permission:
          bundle-id: "com.apple.Terminal"
          permission-type: "kTCCServiceScreenCapture"
      - capture:
          after: 60

workflows:
  main:
    jobs:
      - screencapture
