version: 2.1

jobs:
  dedicated-host:
    macos:
      xcode: "13.3"
    resource_class: macos.x86.metal.gen1
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout

workflows:
  big-mac:
    jobs:
      - dedicated-host
