version: 2.1

orbs:
  node: circleci/node@5

jobs:
  node-install:
    parameters:
      xcode:
        type: string
        default: "14.2.0"
      size:
        type: integer
        default: 5
      use_http_1:
        type: boolean
        default: false
    macos:
      xcode: << parameters.xcode >>
    resource_class: macos.x86.medium.gen2
    parallelism: << parameters.size >>
    steps:
      - when:
          condition: << parameters.use_http_1 >>
          steps:
            # enforce HTTP/1.1
            # see https://blog.csdn.net/MRlaochen/article/details/125381478
            - run: git config --global http.version HTTP/1.1
      - node/install:
          node-version: "16.13"

workflows:
  main:
    jobs:
      - node-install:
          matrix:
            parameters:
              use_http_1:
                - true
                - false
